<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Hom-Dev03" failures="1" tests="3" name="Default test" time="91.839" errors="0" timestamp="2019-12-31T10:45:48 MST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="25.2"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="42.919">
    <failure type="java.lang.AssertionError" message="expected [11] but found [12]">
      <![CDATA[java.lang.AssertionError: expected [11] but found [12]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at stepDefinitions.license.CEDCampaignGroup.user_exports_the_campaign_groups(CEDCampaignGroup.java:94)
at âœ½.User exports the campaign groups(src/test/resources/features/license/CEDCampaignGroup.feature:16)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="22.224"/>
</testsuite> <!-- Default test -->
